### ISSUE TITLE
Exception when deleting node

### ISSUE THREAD

**Issue by eduramiba** [gephi/graphstore#129]
java.lang.ArrayIndexOutOfBoundsException: 0
    at org.gephi.graph.impl.TimeIndexImpl.remove(TimeIndexImpl.java:68)
    at org.gephi.graph.impl.TimeIndexStore.clear(TimeIndexStore.java:211)
    at org.gephi.graph.impl.ElementImpl.clearAttributes(ElementImpl.java:643)
    at org.gephi.graph.impl.NodeStore.remove(NodeStore.java:279)
    at org.gephi.graph.impl.GraphStore.removeNode(GraphStore.java:244)
    at org.gephi.datalab.impl.GraphElementsControllerImpl.removeNode(GraphElementsControllerImpl.java:454)
    at org.gephi.datalab.impl.GraphElementsControllerImpl.deleteNodes(GraphElementsControllerImpl.java:187)
    at org.gephi.datalab.plugin.manipulators.nodes.DeleteNodes.execute(DeleteNodes.java:70)
[catch] at org.gephi.datalab.api.DataLaboratoryHelper$5.run(DataLaboratoryHelper.java:325)

**Comment by eduramiba** [comment]
Probaly due to lack of locking/synchronization in TimeIndexStore.java
