### ISSUE TITLE
NPE on NodeStore.checkNodeExists

### ISSUE THREAD

**Issue by mbastian** [gephi/graphstore#167]
https://gephi.sentry.io/issues/3953889787/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.graph.impl.NodeStore.checkNodeExists(NodeStore.java:542)
    at org.gephi.graph.impl.GraphViewImpl.removeNode(GraphViewImpl.java:220)
    at org.gephi.graph.impl.GraphViewImpl.retainNodes(GraphViewImpl.java:284)
    at org.gephi.graph.impl.GraphViewDecorator.retainNodes(GraphViewDecorator.java:271)
    at org.gephi.desktop.search.filter.SearchFilterBuilder$SearchFilter.filter(SearchFilterBuilder.java:89)
...
(3 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
Can't reproduce for now. Might be caused by some previous operations that leaves the view in an inconsistent state.
